config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :statuses
  resources :priorities
  resources :verticals
  resources :request_types
  resources :roles
  resources :tasks

  devise_for :users
    resources :users do
      member do
        get ':type/serve_avatar', action: 'serve_avatar'
        put :approve
      end
    end

  devise_scope :user do
    authenticated :user do
      root 'tasks#index', as: :authenticated_root
    end
  end
  root 'devise/sessions#new'

  get  '/new_user_no_devise',  to: 'users#new'
  post '/create_user_no_devise', to: 'users#create'

  patch '/update_user_no_devise/:id', to: 'users#update'
  patch '/changepw', to: 'users#changepw'


  get '/delete_avatar', to: 'users#destroy_avatar'
  get ':id/:type/serve_doc', to: 'attachments#serve_doc'
  get '/delete_doc', to: 'attachments#destroy'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  load_and_authorize_resource
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: t('status.successfully-created') }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: t('status.successfully-updated') }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    message = ""
    message_type = "notice"
    if @status.destroy
      message = t('status.successfully-destroyed')
    else
      message_type = "alert"
      unless @status.errors.full_messages.blank?
        @status.errors.full_messages.each do | error_message |
          message += error_message +". "
        end
      else
        message = t('status.not-destroyed')
      end
    end
    respond_to do |format|
      if message_type == "alert"
        format.html { redirect_to statuses_url, alert: message }
        format.json { head :no_content }
      else
        format.html { redirect_to statuses_url, notice: message }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:name, :description)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<div class="form_div">
  <%= form_for(status) do |f| %>
    <% if status.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>
        <ul>
          <% status.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class:"simple_input" %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description, class:"simple_input" %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/statuses/edit.html.erb
<h1 class="object_title">Editing Status</h1>

<%= render 'form', status: @status %>

<div class="bottom_link">
  <%= link_to 'Show', @status %> |
  <%= link_to 'Back', statuses_path %>
</div>

app/views/statuses/index.html.erb
<h1 class="object_title">Statuses</h1>

<table class="table table-responsive table-hover table-bordered sub_data">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.name %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<div class="bottom_link" >
  <%= link_to 'New Status', new_status_path %>
</div>

app/views/statuses/new.html.erb
<h1 class="object_title">New Status</h1>

<%= render 'form', status: @status %>

<div class="bottom_link">
  <%= link_to 'Back', statuses_path %>
</div>

app/views/statuses/show.html.erb
<div class="show_div">
  <p>
    <strong>Name:</strong>
    <%= @status.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @status.description %>
  </p>

  <%= link_to 'Edit', edit_status_path(@status) %> |
  <%= link_to 'Back', statuses_path %>
</div>