config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :statuses
  resources :priorities
  resources :verticals
  resources :request_types
  resources :roles
  resources :tasks

  devise_for :users
    resources :users do
      member do
        get ':type/serve_avatar', action: 'serve_avatar'
        put :approve
      end
    end

  devise_scope :user do
    authenticated :user do
      root 'tasks#index', as: :authenticated_root
    end
  end
  root 'devise/sessions#new'

  get  '/new_user_no_devise',  to: 'users#new'
  post '/create_user_no_devise', to: 'users#create'

  patch '/update_user_no_devise/:id', to: 'users#update'
  patch '/changepw', to: 'users#changepw'


  get '/delete_avatar', to: 'users#destroy_avatar'
  get ':id/:type/serve_doc', to: 'attachments#serve_doc'
  get '/delete_doc', to: 'attachments#destroy'

end

app/models/vertical.rb
class Vertical < ApplicationRecord
  has_many :tasks, dependent: :restrict_with_error
end

app/controllers/verticals_controller.rb
class VerticalsController < ApplicationController
  load_and_authorize_resource
  before_action :set_vertical, only: [:show, :edit, :update, :destroy]

  # GET /verticals
  # GET /verticals.json
  def index
    @verticals = Vertical.all
  end

  # GET /verticals/1
  # GET /verticals/1.json
  def show
  end

  # GET /verticals/new
  def new
    @vertical = Vertical.new
  end

  # GET /verticals/1/edit
  def edit
  end

  # POST /verticals
  # POST /verticals.json
  def create
    @vertical = Vertical.new(vertical_params)
    respond_to do |format|
      if @vertical.save
        format.html { redirect_to @vertical, notice: t('vertical.successfully-created') }
        format.json { render :show, status: :created, location: @vertical }
      else
        format.html { render :new }
        format.json { render json: @vertical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verticals/1
  # PATCH/PUT /verticals/1.json
  def update
    respond_to do |format|
      if @vertical.update(vertical_params)
        format.html { redirect_to @vertical, notice: t('vertical.successfully-updated') }
        format.json { render :show, status: :ok, location: @vertical }
      else
        format.html { render :edit }
        format.json { render json: @vertical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verticals/1
  # DELETE /verticals/1.json
  def destroy
    message = ""
    message_type = "notice"
    if @vertical.destroy
      message = t('vertical.successfully-destroyed')
    else
      message_type = "alert"
      unless @vertical.errors.full_messages.blank?
        @vertical.errors.full_messages.each do | error_message |
          message += error_message +". "
        end
      else
        message = t('vertical.not-destroyed')
      end
    end
    respond_to do |format|
      if message_type == "alert"
        format.html { redirect_to priorities_url, alert: message }
        format.json { head :no_content }
      else
        format.html { redirect_to priorities_url, notice: message }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_vertical
      @vertical = Vertical.find(params[:id])
    end

    def vertical_params
      params.require(:vertical).permit(:name, :description)
    end
end

app/helpers/verticals_helper.rb
module VerticalsHelper
end

app/views/verticals/_form.html.erb
<div class="form_div">
  <%= form_for(vertical) do |f| %>
    <% if vertical.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(vertical.errors.count, "error") %> prohibited this vertical from being saved:</h2>

        <ul>
        <% vertical.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class:"simple_input" %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description, class:"simple_input" %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/verticals/edit.html.erb
<h1 class="object_title">Editing Vertical</h1>

<%= render 'form', vertical: @vertical %>

<div class="bottom_link">
  <%= link_to 'Show', @vertical %> |
  <%= link_to 'Back', verticals_path %>
</div>

app/views/verticals/index.html.erb
<h1 class="object_title">Verticals</h1>

<table class="table table-responsive table-hover table-bordered sub_data">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
    <% @verticals.each do |vertical| %>
      <tr>
        <td><%= vertical.name %></td>
        <td><%= vertical.description %></td>
        <td><%= link_to 'Show', vertical %></td>
        <td><%= link_to 'Edit', edit_vertical_path(vertical) %></td>
        <td><%= link_to 'Destroy', vertical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>

<div class="bottom_link">
  <%= link_to 'New Vertical', new_vertical_path %>
</div>

app/views/verticals/new.html.erb
<h1 class="object_title">New Vertical</h1>

<%= render 'form', vertical: @vertical %>

<div class="bottom_link">
  <%= link_to 'Back', verticals_path %>
</div>

app/views/verticals/show.html.erb
<div class="show_div">
  <p>
    <strong>Name:</strong>
    <%= @vertical.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @vertical.description %>
  </p>

  <%= link_to 'Edit', edit_vertical_path(@vertical) %> |
  <%= link_to 'Back', verticals_path %>
</div>